package com.ecommerce.app.shopify.domain;
// Generated May 3, 2013 2:55:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private long contactId;
     private long profileId;
     private Date changeTime;

    public Contact() {
    }

    public Contact(long contactId, long profileId, Date changeTime) {
       this.contactId = contactId;
       this.profileId = profileId;
       this.changeTime = changeTime;
    }
   
    public long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(long contactId) {
        this.contactId = contactId;
    }
    public long getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(long profileId) {
        this.profileId = profileId;
    }
    public Date getChangeTime() {
        return this.changeTime;
    }
    
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }




}


